### ISSUE TITLE
Should we deprecated the conditional.status helper in favor of upstream? 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lib#10]
Users might be able to use the implementation made in upstream instead. See: https://github.com/kubernetes/kubernetes/pull/92717/files

**Comment by joelanford** [comment]
Closed by #35, where the status package was removed. Users are encouraged to use [`metav1.Condition`](https://pkg.go.dev/k8s.io/apimachinery@v0.19.2/pkg/apis/meta/v1#Condition) with the conditions helpers in the [meta package](https://pkg.go.dev/k8s.io/apimachinery@v0.19.2/pkg/api/meta).
