### ISSUE TITLE
Check the node status when leader re-election.

### ISSUE THREAD

**Issue by kasonglee** [operator-framework/operator-lib#24]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I have an issue when (...)"

From leader/leader.go, leader re-election works after the default timeout 5-min since the condition
Pod.status.phase == "Failed" && Pod.Status.Reason == "Evicted" when a worker node is failed.
I have an opinion that leader re-election can work almost immediately when the condition contains checking the status of the node where the leader pod is running.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Check the condition of the node where the leader pod is running with [Node.Type == "NodeReady" && Node.Status != "ConditionTrue"] and when the node has been failed, delete the leaderPod (only mark the pod with 'terminating' because the node where the pod is running has been failed) and the configmap lock whose OwnerReference is leaderPod)

Pictures below are the test of node-check for leader re-election.(test-operator-xxx-xxx**qb** was the leaderPod)

![3](https://user-images.githubusercontent.com/66303838/89374604-d88bef80-d726-11ea-8b56-23f254ef5d58.png)
![4](https://user-images.githubusercontent.com/66303838/89374641-f6f1eb00-d726-11ea-99d5-a58ba91e830c.png)
![5](https://user-images.githubusercontent.com/66303838/89374649-f9ecdb80-d726-11ea-8b45-7dc0e3a3b708.png)

Making --pod-eviction-timeout to be short can be another approach. However, I sure that above approach can bring more reliability since we don't know appropriate time out.

And Is there any drawbacks when making --pod-eviction-timeout to be very very short? 

@HyungJune

**Comment by mhrivnak** [comment]
> And Is there any drawbacks when making --pod-eviction-timeout to be very very short?

The use case for the timeout is that a Node gets temporarily disconnected from the cluster but is then able to re-connect. The shorter the timeout, the more risk that the Node will re-appear and all the workloads on it will try to keep running despite having had their Pods deleted. Probably they would not run for long, but it may take some time for the local kubelet to catch up and stop all the containers.

This scenario greatly benefits from fencing. Ideally you allow a separate component to monitor the Node health, and then take action to ensure that a missing Node will not return before deleting its workloads. This can be done for example by powering off the Node's underlying machine.

**Comment by kasonglee** [comment]
Here's what I understood : "making --pod-eviction-timeout to be very short can be risky because it may take some time for the local kubelet to catch up and stop all the containers. The solution is the component to monitor the node health and ensure that the missing node will not be 'Ready' status until deleting its workloads."

I think that like my case, the operator may need the feature of checking the Node health because of the fast leader re-election. so **I suggest making a separate go-package for checking the Node health in the operator-lib repository** and the package will be used by the operator that run on all the nodes in the cluster (i.e daemon-set).(Of course, I need to modify my code to deleting all workloads on the missing node.)

**Comment by Bryce-huang** [comment]
Is there any solution?

**Comment by Bryce-huang** [comment]
https://github.com/operator-framework/operator-sdk/issues/1813
https://github.com/operator-framework/operator-sdk/issues/784

**Comment by varshaprasad96** [comment]
There is still discussion required on modifying the controller-runtime interface to enable the use of leader for life/lease-based leader election. Since this particular issue concerns about waiting for a default timeout, even when the node status is false and a [PR](https://github.com/operator-framework/operator-lib/pull/25) has already been merged to solve this, I am closing this issue. Please feel free to open another issue, if you would like to have any other modifications in the current (leader for life)  implementation.
