### ISSUE TITLE
Status pkg missing

### ISSUE THREAD

**Issue by imilchev** [operator-framework/operator-lib#37]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I noticed that [here](https://github.com/operator-framework/operator-sdk/pull/3503) it is stated that the `pkg/status` and `pkg/leader` are deleted from the `operator-sdk` because they are moved to this repo. However, I only see `pkg/leader` here and `pkg/status` is still missing. Is this intended?

**Describe the solution you'd like**
Add `pkg/status` in this repo.

**Comment by joelanford** [comment]
We removed `pkg/status` in v0.2.0 because `k8s.io/apimachinery@v0.19.0` added an official implementation for conditions.

If you can't bump your k8s deps to v1.19, You can pin your operator-lib dep to v0.1.0 to continue using `pkg/status`.
