### ISSUE TITLE
handler.InstrumentedEnqueueRequestForOwner

### ISSUE THREAD

**Issue by alebedev87** [operator-framework/operator-lib#52]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'm migrating an operator to a OperatorSDK 1.x and I'm following the migration guide which [suggests](https://sdk.operatorframework.io/docs/building-operators/golang/migration/#use-handler-from-operator-lib) to use `operator-lib/handler` package to have the enqueue methods instrumented with the metrics. The operator I'm migrating needs to watch for a secondary resource whose instances I used to enqueue with controller-runtime's `handler.EnqueueRequestForOwner`. I don't see the equivalent instrumented function in operator-lib's handler package.

**Describe the solution you'd like**
I'm wondering whether there is an easy way to achieve what I just described. Otherwise I'd like to see a method `InstrumentedEnqueueRequestForOwner` in handler's package which would instrument the enqueue action of the secondary resources with the metrics similar to  `InstrumentedEnqueueRequestForObject`.

**Comment by alebedev87** [comment]
Looking at the implementation of controller-runtime's `handler.EnqueueRequestForOwner` [here](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.1/pkg/handler/enqueue_owner.go#L63), it seems that controller's queue is populated with the reconcile requests of the controller for the owned secondary resources.
This means that it's enough to have the primary resource to be watched with the metrics instrumentation as the owned objects will result back into the enqueue requests of the primary resource.
Can you please correct me if I'm wrong in my findings?

**Comment by joelanford** [comment]
Yes, that's correct! The controllers for the secondary resources should be managing the metrics for them. You are just responsible for metrics for your primary resource.
